name: release
on:
  push:
    tags:
      - "v*"
    branches:
      - master # Trigger on pushes to the master branch

jobs:
  build-and-release:
    permissions:
      contents: write # Required to create releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install
        run: npm ci || npm i

      - name: Build
        run: npm run build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the workflow token
          generate_release_notes: true
          files: |
            dist/*.user.js
