name: release
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write # Required to create releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for all tags

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24.8.0"

      - name: Install
        run: npm ci || npm i

      - name: Build
        run: npm run build

      - name: Release
        uses: softprops/action-gh-release@v2.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the workflow token
          generate_release_notes: true
          files: |
            dist/*.user.js
